name: Python application CI/CD

on:
  push:
    branches:
      - main
      - develop

## Build dependencies
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

## Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir --upgrade -r requirements.txt

## Test with unittest
    - name: Test with unittest
      run: |
        python -m unittest discover tests

## deploy sonarcloud with github
    - uses: actions/checkout@v3
      with:
            # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_TOKEN: "c84f12a9a1db470b759cf1107822db8860cf8ea1"

## Build and push docker image
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      if: success()
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: devco/fast-api-example:latest
        #