name: Python application CI/CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir --upgrade -r requirements.txt

    - name: Test with unittest
      run: |
        python -m unittest discover tests

    - name: Build and push Docker image
      if: success()
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: devco/fast-api-example:latest

    - name: Deploy to Docker
      if: success()
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          docker pull devco/fast-api-example:latest
          docker stop fast-api-example || true
          docker rm fast-api-example || true
          docker run --name fast-api-example -d -p 8000:8000 devco/fast-api-example:latest
